locale: fr
backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img

# local_backend: true

collections:
  - name: partenaires
    label: Partenaires
    label_singular: Partenaire
    identifier_field: name
    folder: "data/partenaires"
    create: true
    editor:
      preview: false
    slug: "{{name}}"
    format: yml
    fields:
      - label: Nom de votre institution
        hint: Département de la Gironde, Ville de Canéjan, Mauges Communauté, etc.
        name: name
        widget: string
      - label: Logo
        name: imgSrc
        widget: image
        allow_multiple: false
      - label: Aides de test
        label_singular: aide de test
        name: testing_benefits
        widget: list
         hint: Vous pouvez ajouter une première aide pour vous appropriez le fonctionnement collaboratif du simulateur.
        default: []
        collapsed: false
        fields:
          - label: Nom
            name: name
            hint: Aide aux impayés de loyer, Chèque de Nöel, etc.
            widget: string
          - label: Code du département
            name: geographic_sector
            widget: string
            hint: 33 pour la Gironde, l'aide ne sera affichée que pour les personnes ayant déclaré vivre dans ce département.
          - label: Lien vers la page d'informations de référence
            hint: Ce lien permet aux usagers d'aller plus loin dans leurs démarches et de bénéficier effectivement de l'aide. Il est préférable d'indiquer un lien vers un site institutionnel.
            name: link
            widget: string
  - name: contribution-pages
    label: Pages du site pour contribuer
    files:
    - label: Accueil
      name: accueil
      file: "contribuer/content/home.md"
      fields:
        - { label: Titre, name: title, widget: string}
        - { label: Corps, name: body, widget: markdown}
        - label: Contributions
          name: categories
          widget: list
          fields:
            - { label: Nom, name: name, widget: string}
            - label: Idées
              name: ideas
              widget: list
              field: { label: Nom, name: name, widget: string }
  - name: tasks
    label: Contributions possibles
    label_singular: Contribution possible
    folder: "contribuer/content/tasks"
    create: true
    delete: false
    slug: "{{slug}}"
    fields:
      - { label: Nom, name: title, widget: string }
      - { label: Description, name: "body", widget: "markdown", required: false }
