locale: fr
backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: Création de {{slug}} dans {{collection}}
    update: Mise à jour de {{slug}} dans {{collection}}
    delete: Suppression de {{slug}} dans {{collection}}
    uploadMedia: Nouvelle image {{path}}
    deleteMedia: Suppression de l'image {{path}}

media_folder: public/img
public_folder: img

# local_backend: true
publish_mode: editorial_workflow

root: ../../..

collections:
  - name: partenaires
    label: Partenaires
    label_singular: partenaire
    identifier_field: name
    folder: "data/partenaires"
    create: true
    delete: false
    editor:
      preview: false
    slug: "{{name}}"
    extension: yml
    fields:
      - label: Nom de votre institution
        hint: Département de la Gironde, Ville de Canéjan, Mauges Communauté, etc.
        name: name
        widget: string
      - label: Logo
        name: imgSrc
        widget: image
        allow_multiple: false
      - label: aides fictives
        label_singular: aide fictive
        name: testing_benefits
        widget: list
        hint: Pour expérimenter la contribution sur Mes Aides, vous pouvez ajouter une aide, fictive. C'est une aide simplifiée mais cet premier ajout nous semble être une étape importante et nécessaire pour s'approprier les modalités de contribution.
        default: []
        collapsed: false
        fields:
          - label: Nom
            name: name
            hint: Aide aux impayés de loyer, Chèque de Nöel, etc.
            widget: string
          - label: Lien vers la page d'informations de référence
            hint: Ce lien permet aux usagers d'aller plus loin dans leurs démarches et de bénéficier effectivement de l'aide. Il est préférable d'indiquer un lien vers un site institutionnel.
            name: link
            widget: string
  - name: contribution-pages
    label: Pages
    label_singular: page
    create: true
    delete: false
    files:
    - label: Accueil
      name: accueil
      file: "contribuer/content/home.md"
      fields:
        - { label: Titre, name: title, widget: string}
        - { label: Corps, name: body, widget: markdown}
        - label: Contributions
          name: categories
          widget: list
          fields:
            - { label: Nom, name: name, widget: string}
            - label: Idées
              name: ideas
              widget: list
              field: { label: Nom, name: name, widget: string }
  - name: tasks
    label: Contributions
    label_singular: contribution
    folder: "contribuer/content/tasks"
    create: true
    delete: false
    slug: "{{slug}}"
    fields:
      - { label: Nom, name: title, widget: string }
      - { label: Description, name: "body", widget: "markdown", required: false }
